CREATE DATABASE MARKET

USE MARKET

CREATE TABLE ISCI(
ID INT PRIMARY KEY IDENTITY,
SAA NVARCHAR(100),
VEZIFEID INT REFERENCES VEZIFE(ID),
MAAS INT
)

CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(100)
)

CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(100)
)

CREATE TABLE MEHSUL(
ID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(100),
ALISQIYMETI FLOAT,
SATISQIYMETI FLOAT
)

CREATE TABLE SATIS(
ID INT PRIMARY KEY IDENTITY,
MEHSULID INT REFERENCES MEHSUL(ID),
ISCIID INT REFERENCES ISCI(ID),
FILIALID INT REFERENCES FILIAL(ID),
SATISTARIXI DATE
)



SELECT I.SAA,M.AD 'MEHSUL ADI',F.AD 'FILIAL ADI',M.ALISQIYMETI,M.SATISQIYMETI FROM SATIS AS S  --------------1
JOIN ISCI AS I
ON I.ID=S.ISCIID
JOIN MEHSUL AS M
ON M.ID=S.MEHSULID
JOIN FILIAL AS F
ON F.ID=S.FILIALID


SELECT* FROM SATIS AS S  -----------------2XXXXXXXXXXXXX
JOIN MEHSUL AS M
ON M.ID=S.MEHSULID


SELECT SUM(SATISQIYMETI) FROM MEHSUL AS M                -----------------3
JOIN SATIS AS S
ON S.MEHSULID=M.ID
WHERE datepart(mm, S.SATISTARIXI) =month(getdate())


 SELECT * FROM SATIS AS S           -----------4XXXXXXXXXX
 JOIN MEHSUL AS M
 ON M.ID=S.MEHSULID
 JOIN ISCI AS I
 ON I.ID=S.ISCIID
 GROUP BY I.SAA
 















